"""Deterministic analysis agent with LLM-powered summary.

The analysis itself is pure computation — significance tests, element
attribution, interaction effects, and fatigue detection all use scipy
and deterministic Python. Only the natural-language summary is
generated by the LLM.
"""

from __future__ import annotations

import json
import logging
from collections import defaultdict
from decimal import Decimal
from typing import TYPE_CHECKING
from uuid import UUID

import anthropic

from src.exceptions import LLMError
from src.models.analysis import (
    AnalysisResult,
    ElementInsight,
    InteractionInsight,
    VariantSignificanceResult,
)
from src.models.variant import VariantStatus
from src.services.fatigue import detect_fatigue
from src.services.interactions import compute_interactions
from src.services.stats import (
    compare_variants,
    element_significance,
    has_sufficient_data,
)
from src.services.usage import AgentContext, log_llm_call

if TYPE_CHECKING:
    from sqlalchemy.ext.asyncio import AsyncSession

    from src.models.metrics import DailyRollup
    from src.models.variant import VariantResponse

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# System prompt for the summary-generation step (the ONLY LLM usage).
# ---------------------------------------------------------------------------

SUMMARY_SYSTEM_PROMPT = """\
You are an analyst summarizing the results of an ad creative optimization cycle. \
You will receive structured analysis data (significance tests, element performance, \
interaction effects, fatigue signals). Your job is to produce a clear, actionable \
natural-language summary for the marketing team.

RULES:
1. Be concise — two to four paragraphs maximum.
2. Lead with the most important finding (e.g., a new winner, a fatigued variant).
3. Call out specific variant codes, element values, and numbers.
4. Recommend next steps based on the data.
5. Never invent statistics — only reference numbers from the data provided.
6. Use plain language, not jargon.

Call the `write_summary` tool with your summary text.
"""


def _build_summary_tool() -> dict:
    """Tool schema for the LLM summary output."""
    return {
        "name": "write_summary",
        "description": "Write the natural-language cycle analysis summary.",
        "input_schema": {
            "type": "object",
            "properties": {
                "summary": {
                    "type": "string",
                    "description": (
                        "A concise (2-4 paragraph) natural-language summary of "
                        "the analysis cycle for the marketing team."
                    ),
                },
            },
            "required": ["summary"],
        },
    }


# ---------------------------------------------------------------------------
# Internal data class for aggregated metrics per variant.
# ---------------------------------------------------------------------------


class _AggregatedMetrics:
    """Simple container for aggregated metrics of a single variant."""

    __slots__ = ("impressions", "clicks", "conversions", "spend")

    def __init__(
        self,
        impressions: int = 0,
        clicks: int = 0,
        conversions: int = 0,
        spend: Decimal = Decimal("0"),
    ) -> None:
        self.impressions = impressions
        self.clicks = clicks
        self.conversions = conversions
        self.spend = spend


def _aggregate_metrics(daily_rollups: list[DailyRollup]) -> _AggregatedMetrics:
    """Sum daily rollups into a single aggregate."""
    agg = _AggregatedMetrics()
    for rollup in daily_rollups:
        agg.impressions += rollup.impressions
        agg.clicks += rollup.clicks
        agg.conversions += rollup.conversions
        agg.spend += rollup.spend
    return agg


# ---------------------------------------------------------------------------
# Pure-computation helpers — no LLM calls.
# ---------------------------------------------------------------------------


def _compute_element_insights(
    variants: list[VariantResponse],
    metrics_by_variant: dict[UUID, _AggregatedMetrics],
    global_mean_ctr: float,
) -> list[ElementInsight]:
    """Aggregate performance data per gene-pool element across all variants.

    For each unique (slot_name, slot_value) pair, collects CTR from every
    variant that uses that element and runs a t-test against the global mean
    using ``element_attribution`` from the stats service.
    """
    element_data: dict[tuple[str, str], list[tuple[float, int, int]]] = defaultdict(list)

    for variant in variants:
        agg = metrics_by_variant.get(variant.id)
        if agg is None or agg.impressions == 0:
            continue
        ctr = agg.clicks / agg.impressions
        for slot_name, slot_value in variant.genome.items():
            element_data[(slot_name, slot_value)].append((ctr, agg.impressions, agg.conversions))

    insights: list[ElementInsight] = []
    for (slot_name, slot_value), entries in element_data.items():
        variant_ctrs = [(ctr, imps) for ctr, imps, _ in entries]
        ctrs_only = [ctr for ctr, _, _ in entries]
        total_impressions = sum(imps for _, imps, _ in entries)
        total_conversions = sum(conv for _, _, conv in entries)

        # Compute weighted average CTR
        total_imps = sum(imps for _, imps, _ in entries)
        weighted_avg_ctr = (
            sum(ctr * imps for ctr, imps, _ in entries) / total_imps if total_imps > 0 else 0.0
        )
        # Significance test via one-sample t-test
        _t_stat, _p_val, confidence = element_significance(
            element_ctrs=ctrs_only,
            global_mean_ctr=global_mean_ctr,
        )

        insights.append(
            ElementInsight(
                slot_name=slot_name,
                slot_value=slot_value,
                variants_tested=len(entries),
                avg_ctr=Decimal(str(round(weighted_avg_ctr, 6))),
                avg_cpa=None,
                best_ctr=Decimal(str(round(max(ctrs_only), 6))) if ctrs_only else None,
                worst_ctr=Decimal(str(round(min(ctrs_only), 6))) if ctrs_only else None,
                total_impressions=total_impressions,
                total_conversions=total_conversions,
                confidence=Decimal(str(round(confidence, 2))),
            )
        )

    return sorted(insights, key=lambda i: float(i.avg_ctr), reverse=True)


def _compute_interaction_insights(
    variants: list[VariantResponse],
    metrics_by_variant: dict[UUID, _AggregatedMetrics],
) -> list[InteractionInsight]:
    """Compute pairwise interaction lift for all element pairs.

    Delegates the heavy lifting to ``compute_interactions`` from the
    interactions service, then maps results to the Pydantic model.
    """
    variants_with_metrics: list[tuple[dict[str, str], float]] = []
    for variant in variants:
        agg = metrics_by_variant.get(variant.id)
        if agg is None or agg.impressions == 0:
            continue
        ctr = agg.clicks / agg.impressions
        variants_with_metrics.append((variant.genome, ctr))

    raw_results = compute_interactions(
        variants_with_metrics=variants_with_metrics,
        min_combined_variants=2,
    )

    insights: list[InteractionInsight] = []
    for r in raw_results:
        insights.append(
            InteractionInsight(
                slot_a_name=r.slot_a_name,
                slot_a_value=r.slot_a_value,
                slot_b_name=r.slot_b_name,
                slot_b_value=r.slot_b_value,
                variants_tested=r.variants_combined,
                combined_avg_ctr=Decimal(str(round(r.combined_avg_ctr, 6))),
                solo_a_avg_ctr=Decimal(str(round(r.solo_a_avg_ctr, 6))),
                solo_b_avg_ctr=Decimal(str(round(r.solo_b_avg_ctr, 6))),
                interaction_lift=Decimal(str(round(r.lift, 6))),
                confidence=None,
            )
        )

    return insights


def _detect_fatigued_variants(
    daily_rollups_by_variant: dict[UUID, list[DailyRollup]],
    consecutive_decline_days: int = 3,
) -> list[UUID]:
    """Detect variants with CTR declining for N+ consecutive days.

    Uses ``detect_fatigue`` from the fatigue service.

    Args:
        daily_rollups_by_variant: Mapping of variant_id to its daily rollups.
        consecutive_decline_days: How many consecutive declining days trigger
            a fatigue flag. Default 3 per CLAUDE.md.

    Returns:
        List of variant IDs exhibiting fatigue.
    """
    fatigued: list[UUID] = []

    for variant_id, rollups in daily_rollups_by_variant.items():
        daily_ctrs: list[tuple] = [(r.day, float(r.ctr)) for r in rollups]

        result = detect_fatigue(
            daily_ctrs=daily_ctrs,
            window=consecutive_decline_days,
        )

        if result.is_fatigued:
            fatigued.append(variant_id)
            logger.warning(
                "Fatigue detected: variant=%s declining_days=%d slope=%.5f",
                variant_id,
                result.consecutive_decline_days,
                result.trend_slope,
            )

    return fatigued


# ---------------------------------------------------------------------------
# Main analyst agent class.
# ---------------------------------------------------------------------------


class AnalystAgent:
    """Runs deterministic analysis on campaign data and generates an LLM summary.

    The statistical analysis (significance tests, element attribution,
    interaction effects, fatigue detection) is 100% deterministic Python
    using scipy.stats. The LLM is used ONLY to produce a human-readable
    summary of the results.

    Args:
        client: An initialized ``anthropic.AsyncAnthropic`` client.
        model: The Anthropic model identifier to use.
    """

    def __init__(
        self,
        client: anthropic.AsyncAnthropic,
        model: str,
        usage_session: AsyncSession | None = None,
        usage_context: AgentContext | None = None,
    ) -> None:
        self._client = client
        self._model = model
        # Phase E cost-attribution hooks. See GeneratorAgent for the
        # same pattern — both args must be set to enable logging.
        self._usage_session = usage_session
        self._usage_context = usage_context

    async def analyze_cycle(
        self,
        campaign_id: UUID,
        cycle_number: int,
        variants: list[VariantResponse],
        daily_rollups_by_variant: dict[UUID, list[DailyRollup]],
        baseline_variant_id: UUID | None = None,
        confidence_threshold: float = 0.95,
        min_impressions: int = 1000,
    ) -> AnalysisResult:
        """Run a full analysis cycle.

        Steps (all deterministic except the final summary):
          a. Aggregate metrics per variant
          b. Run significance tests for each variant vs. baseline
          c. Compute element-level performance attribution
          d. Compute pairwise interaction effects
          e. Detect audience fatigue
          f. Determine actions (winners to promote, losers to pause)
          g. Generate LLM summary (the ONLY LLM call)

        Args:
            campaign_id: The campaign being analyzed.
            cycle_number: Monotonically increasing cycle counter.
            variants: All variants in the campaign.
            daily_rollups_by_variant: Daily metrics keyed by variant ID.
            baseline_variant_id: The variant to compare others against.
                If None, uses the variant with the most impressions.
            confidence_threshold: Significance level (e.g. 0.95 means
                p_value < 0.05 is significant).
            min_impressions: Minimum impressions before testing.

        Returns:
            A fully populated AnalysisResult.
        """
        # Convert confidence_threshold to alpha for p-value comparison.
        # CLAUDE.md says confidence_threshold defaults to 0.95, meaning
        # a variant is significant when p_value < (1 - 0.95) = 0.05.
        alpha = 1.0 - confidence_threshold

        # Step (a): Aggregate metrics
        metrics_by_variant: dict[UUID, _AggregatedMetrics] = {}
        for variant_id, rollups in daily_rollups_by_variant.items():
            metrics_by_variant[variant_id] = _aggregate_metrics(rollups)

        # Step (b): Determine baseline
        if baseline_variant_id is None:
            baseline_variant_id = self._pick_baseline(variants, metrics_by_variant)

        baseline_agg = metrics_by_variant.get(baseline_variant_id)
        if baseline_agg is None or baseline_agg.impressions == 0:
            baseline_clicks = 0
            baseline_impressions = 0
        else:
            baseline_clicks = baseline_agg.clicks
            baseline_impressions = baseline_agg.impressions

        # Step (c): Significance tests
        variant_results = self._run_significance_tests(
            variants=variants,
            metrics_by_variant=metrics_by_variant,
            baseline_variant_id=baseline_variant_id,
            baseline_clicks=baseline_clicks,
            baseline_impressions=baseline_impressions,
            alpha=alpha,
            min_impressions=min_impressions,
        )

        # Step (d): Element performance attribution
        global_clicks = sum(a.clicks for a in metrics_by_variant.values())
        global_impressions = sum(a.impressions for a in metrics_by_variant.values())
        global_mean_ctr = global_clicks / global_impressions if global_impressions > 0 else 0.0

        element_insights = _compute_element_insights(
            variants=variants,
            metrics_by_variant=metrics_by_variant,
            global_mean_ctr=global_mean_ctr,
        )

        # Step (e): Interaction effects
        interaction_insights = _compute_interaction_insights(
            variants=variants,
            metrics_by_variant=metrics_by_variant,
        )

        # Step (f): Fatigue detection
        fatigued_variants = _detect_fatigued_variants(daily_rollups_by_variant)

        # Step (g): LLM summary
        summary = await self._generate_summary(
            campaign_id=campaign_id,
            cycle_number=cycle_number,
            variant_results=variant_results,
            element_insights=element_insights,
            interaction_insights=interaction_insights,
            fatigued_variants=fatigued_variants,
        )

        return AnalysisResult(
            campaign_id=campaign_id,
            cycle_number=cycle_number,
            variant_results=variant_results,
            element_insights=element_insights,
            interaction_insights=interaction_insights,
            fatigued_variants=fatigued_variants,
            summary=summary,
        )

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _pick_baseline(
        variants: list[VariantResponse],
        metrics_by_variant: dict[UUID, _AggregatedMetrics],
    ) -> UUID:
        """Select the baseline variant (most impressions)."""
        best_id: UUID | None = None
        best_impressions = -1
        for v in variants:
            agg = metrics_by_variant.get(v.id)
            imps = agg.impressions if agg else 0
            if imps > best_impressions:
                best_impressions = imps
                best_id = v.id
        if best_id is None:
            return variants[0].id
        return best_id

    @staticmethod
    def _run_significance_tests(
        variants: list[VariantResponse],
        metrics_by_variant: dict[UUID, _AggregatedMetrics],
        baseline_variant_id: UUID,
        baseline_clicks: int,
        baseline_impressions: int,
        alpha: float,
        min_impressions: int,
    ) -> list[VariantSignificanceResult]:
        """Run two-proportion z-tests for each variant vs. the baseline.

        Uses ``two_proportion_z_test`` and ``is_significant`` from the
        stats service. Variants without sufficient data are skipped.
        """
        baseline_ctr = baseline_clicks / baseline_impressions if baseline_impressions > 0 else 0.0
        results: list[VariantSignificanceResult] = []

        for variant in variants:
            if variant.id == baseline_variant_id:
                continue

            agg = metrics_by_variant.get(variant.id)
            if agg is None or not has_sufficient_data(agg.impressions, min_impressions):
                continue

            variant_ctr = agg.clicks / agg.impressions if agg.impressions > 0 else 0.0

            _z_stat, p_value, sig = compare_variants(
                baseline_clicks=baseline_clicks,
                baseline_impressions=baseline_impressions,
                variant_clicks=agg.clicks,
                variant_impressions=agg.impressions,
                confidence_threshold=1.0 - alpha,
            )

            # Determine recommended action
            if sig and variant_ctr > baseline_ctr:
                recommended = VariantStatus.WINNER
            elif sig and variant_ctr < baseline_ctr:
                recommended = VariantStatus.PAUSED
            else:
                recommended = VariantStatus.ACTIVE

            results.append(
                VariantSignificanceResult(
                    variant_id=variant.id,
                    variant_code=variant.variant_code,
                    ctr=Decimal(str(round(variant_ctr, 6))),
                    baseline_ctr=Decimal(str(round(baseline_ctr, 6))),
                    p_value=p_value,
                    is_significant=sig,
                    recommended_action=recommended,
                )
            )

        winners = [r for r in results if r.recommended_action == VariantStatus.WINNER]
        losers = [r for r in results if r.recommended_action == VariantStatus.PAUSED]
        logger.info(
            "Significance tests: %d winners, %d losers out of %d tested",
            len(winners),
            len(losers),
            len(results),
        )

        return results

    async def _generate_summary(
        self,
        campaign_id: UUID,
        cycle_number: int,
        variant_results: list[VariantSignificanceResult],
        element_insights: list[ElementInsight],
        interaction_insights: list[InteractionInsight],
        fatigued_variants: list[UUID],
    ) -> str:
        """Call the LLM to produce a natural-language summary.

        This is the ONLY place in the analyst that touches the LLM.
        All data passed in has been computed deterministically.
        """
        data_payload = {
            "campaign_id": str(campaign_id),
            "cycle_number": cycle_number,
            "variant_results": [
                {
                    "variant_code": vr.variant_code,
                    "ctr": float(vr.ctr),
                    "baseline_ctr": float(vr.baseline_ctr),
                    "p_value": vr.p_value,
                    "is_significant": vr.is_significant,
                    "recommended_action": vr.recommended_action.value,
                }
                for vr in variant_results
            ],
            "top_elements": [
                {
                    "slot": ei.slot_name,
                    "value": ei.slot_value,
                    "avg_ctr": float(ei.avg_ctr),
                    "variants_tested": ei.variants_tested,
                    "confidence": float(ei.confidence) if ei.confidence else None,
                }
                for ei in element_insights[:10]
            ],
            "top_interactions": [
                {
                    "pair": (
                        f"{ii.slot_a_name}:{ii.slot_a_value} + {ii.slot_b_name}:{ii.slot_b_value}"
                    ),
                    "lift": float(ii.interaction_lift) if ii.interaction_lift is not None else None,
                    "combined_ctr": float(ii.combined_avg_ctr),
                }
                for ii in interaction_insights[:5]
            ],
            "fatigued_variant_count": len(fatigued_variants),
        }

        user_message = (
            f"Here are the analysis results for cycle {cycle_number}:\n\n"
            f"```json\n{json.dumps(data_payload, indent=2)}\n```\n\n"
            "Write a concise summary using the write_summary tool."
        )

        logger.debug(
            "Analyst summary prompt for campaign %s cycle %d:\nSystem: %s\nUser: %s",
            campaign_id,
            cycle_number,
            SUMMARY_SYSTEM_PROMPT,
            user_message,
        )

        tool = _build_summary_tool()

        try:
            response = await self._client.messages.create(
                model=self._model,
                max_tokens=1024,
                system=SUMMARY_SYSTEM_PROMPT,
                tools=[tool],
                tool_choice={"type": "any"},
                messages=[{"role": "user", "content": user_message}],
            )
        except anthropic.APIError as exc:
            logger.error(
                "Anthropic API error during summary generation: %s (status=%s)",
                exc,
                getattr(exc, "status_code", None),
            )
            raise LLMError(f"Anthropic API call failed: {exc}") from exc

        logger.debug(
            "Analyst summary response: stop_reason=%s, content_blocks=%d, "
            "input_tokens=%d, output_tokens=%d",
            response.stop_reason,
            len(response.content),
            response.usage.input_tokens,
            response.usage.output_tokens,
        )

        if self._usage_session is not None and self._usage_context is not None:
            try:
                await log_llm_call(
                    self._usage_session,
                    self._usage_context,
                    model=self._model,
                    input_tokens=int(response.usage.input_tokens),
                    output_tokens=int(response.usage.output_tokens),
                    metadata={"stop_reason": response.stop_reason},
                )
            except Exception as log_exc:  # noqa: BLE001
                logger.warning("Failed to log analyst usage: %s", log_exc)

        # Extract the summary from the tool-use response
        for block in response.content:
            if block.type == "tool_use" and block.name == "write_summary":
                summary_text = block.input.get("summary", "")
                if summary_text:
                    logger.info(
                        "Generated summary for campaign %s cycle %d (%d chars)",
                        campaign_id,
                        cycle_number,
                        len(summary_text),
                    )
                    return summary_text

        # Fallback: check for plain text blocks (LLM didn't use the tool)
        for block in response.content:
            if block.type == "text" and block.text.strip():
                logger.warning(
                    "LLM returned summary as plain text instead of tool use — "
                    "accepting it but this should be investigated."
                )
                return block.text.strip()

        logger.error("LLM failed to produce a summary for cycle %d", cycle_number)
        raise LLMError(
            f"LLM failed to produce a summary for campaign {campaign_id} cycle {cycle_number}."
        )
